AWSTemplateFormatVersion: "2010-09-09"
Description: Portfolio Cloud
Parameters:
    BucketNameArgument:
        Type: String
    DomainName:
      Type: String
    HostedZoneId:
      Type: String
    AcmCertificate:
      Type: String
Resources:
    BenTrettinPortfolioS3:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketNameArgument
            AccessControl: PublicRead
